title = "Replicator"
languageCode = "en-us"
baseurl = "https://replicator.game"
[params]
  github = "https://github.com/astropuffin/replicator.game"
  description = "A game about real evolution"
  stripeApiKey = "pk_live_R365PMWpNFqjoCstn37sPa1H"
