title = "Replicator"
languageCode = "en-us"
baseurl = "https://replicatorgame.com"
theme = "hugoscroll"
[params]
  github = "https://github.com/astropuffin/replicatorgamecom"
  description = "A game about real evolution in a simulated world"
  stripeEndpoint = "https://replicatorgame.com/v1/payment"
  stripeApiKey = "pk_test_3L5GNZ5lEEJNakPcETm0UO9k"
